/**
 * Legacy lineage:
 * - setup/pi/envsetup.sh (ENV var names and compatibility mapping)
 */
export const ENV_TO_CONFIG_KEY: Record<string, string> = {
  ARCHIVE_SYSTEM: 'archiveSystem',
  RSYNC_SERVER: 'rsyncServer',
  RSYNC_USER: 'rsyncUser',
  RSYNC_PATH: 'rsyncPath',
  RCLONE_DRIVE: 'rcloneDrive',
  RCLONE_PATH: 'rclonePath',
  ARCHIVE_SERVER: 'archiveServer',
  SHARE_NAME: 'shareName',
  MUSIC_SHARE_NAME: 'musicShareName',
  SHARE_USER: 'shareUser',
  SHARE_PASSWORD: 'sharePassword',
  SHARE_DOMAIN: 'shareDomain',
  CAM_SIZE: 'camSize',
  MUSIC_SIZE: 'musicSize',
  BOOMBOX_SIZE: 'boomboxSize',
  LIGHTSHOW_SIZE: 'lightshowSize',
  ARCHIVE_DELAY: 'archiveDelay',
  ARCHIVE_SAVEDCLIPS: 'archiveSavedclips',
  ARCHIVE_SENTRYCLIPS: 'archiveSentryclips',
  ARCHIVE_TRACKMODECLIPS: 'archiveTrackmodeclips',
  ARCHIVE_RECENTCLIPS: 'archiveRecentclips',
  TRIGGER_FILE_START_ENABLED: 'triggerFileStartEnabled',
  TRIGGER_FILE_SAVED: 'triggerFileSaved',
  TRIGGER_FILE_SENTRY: 'triggerFileSentry',
  TRIGGER_FILE_RECENT: 'triggerFileRecent',
  TRIGGER_FILE_ANY: 'triggerFileAny',
  TESLA_EMAIL: 'teslaEmail',
  TESLA_PASSWORD: 'teslaPassword',
  TESLA_VIN: 'teslaVin',
  TESLAFI_BLE_VIN: 'teslafiBleVin',
  TESSIE_VIN: 'tessieVin',
  TESSIE_API_TOKEN: 'tessieApiToken',
  SENTRY_CASE: 'sentryCase',
  PUSHOVER_ENABLED: 'pushoverEnabled',
  PUSHOVER_USER_KEY: 'pushoverUserKey',
  PUSHOVER_APP_KEY: 'pushoverAppKey',
  GOTIFY_ENABLED: 'gotifyEnabled',
  GOTIFY_DOMAIN: 'gotifyDomain',
  GOTIFY_APP_TOKEN: 'gotifyAppToken',
  GOTIFY_PRIORITY: 'gotifyPriority',
  DISCORD_ENABLED: 'discordEnabled',
  DISCORD_WEBHOOK_URL: 'discordWebhookUrl',
  SLACK_ENABLED: 'slackEnabled',
  SLACK_WEBHOOK_URL: 'slackWebhookUrl',
  TELEGRAM_ENABLED: 'telegramEnabled',
  TELEGRAM_BOT_TOKEN: 'telegramBotToken',
  TELEGRAM_CHAT_ID: 'telegramChatId',
  NTFY_ENABLED: 'ntfyEnabled',
  NTFY_URL: 'ntfyUrl',
  TIME_ZONE: 'timeZone',
  NOTIFICATION_TITLE: 'notificationTitle',
  TESLAUSB_HOSTNAME: 'teslaUSBHostname',
  PUBLIC_API_BASE_URL: 'publicApiBaseUrl',
  PUBLIC_WS_URL: 'publicWsUrl',
  UI_CORS_ORIGINS: 'uiCorsOrigins',
  SYSTEM_STATUS_DEFAULT_GATEWAY: 'systemStatusDefaultGateway',
  SYSTEM_STATUS_PING_PACKET_SIZE: 'systemStatusPingPacketSize',
  UPGRADE_PACKAGES: 'upgradePackages',
  INCREASE_ROOT_SIZE: 'increaseRootSize',
};

export function envKeyToConfigKey(envKey: string): string | null {
  return ENV_TO_CONFIG_KEY[envKey] || null;
}
